### ISSUE TITLE
Backend>Events view is not userfriendly

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#197]
I come back to this issue:
one solution is ok to choose which colums are hidden.
But anyway, there are two sliders: one for the table and the other for the backendpage.
It can be complicated to manage this.
Please have a look: it's much easier, when you take away the table-responsive in the default.php. Then you can move with one slider and the arrow-right! class="table" is enough!

**Comment by mckillo** [comment]
I don't have two horizontal sliders, depend of screen resolution and I have active all columns. In small resolutions screen and mobile device yes, there are 2 sliders. 

When you have a lot of column active, responsive doesn't the best solution in the table. I agree, can be confusing.

From the admin zone (backend), this table is good but if you don't want horizontal scrolling in the table, you can leave it fixed with a minimum width. Joomla does that in the table for article, categories, user and others views.

For me ok, I prefer not to apply responsive style in admin views (backend)

**Comment by Heklaterriol** [comment]
I did some enhancements (shorter table columns titles, less padding in table cells)

See https://github.com/Heklaterriol/JEM-Project/commit/abc8139041087143963ee98e66ba62df1f494588 and https://github.com/Heklaterriol/JEM-Project/commit/e4189e8412bed95e23b824a0bf4489190a3d1862

included in release 2.3.17.3

**Comment by jojo12** [comment]
You leave the "table responsive". I am not happy!

You must think of the following: You forgot, that using an other language can longer the table columns and nothing is better (like that you can test each language!

**Comment by jojo12** [comment]
e.g. https://demo.joomlaeventmanager.net/simplelist/venue/2:berghain
